#!/bin/bash

# This script makes a folder structure and basic LaTeX document 

## Constants

RIGHT_NOW="$(date +"%x %r %Z")"
TIME_STAMP="Updated $RIGHT_NOW by $USER"
SCRIPT="$(basename $0)"

## Functions

make_file_structure(){
    [ -d "./$dir" ] || mkdir "./$dir"
    for subdir in img circuit table tex; do
        [ -d "./$dir$subdir" ] || mkdir -p "./$dir$subdir"
    done
}

write_preamble(){
    cat <<- _EOF_
% $TIME_STAMP

%--Preamble-------------------------------------------------------------
\documentclass{scrartcl} % Use the Koma article class

% add packages here.
\usepackage{siunitx}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage[american,nooldvoltagedirection]{circuitikz}
\usepackage{verbatim}
_EOF_
}

write_body(){
    cat <<- _EOF_
    
%--Body-----------------------------------------------------------------
\begin{document}
    \title{Title}
    \subject{Subtitle}
    \author{Author}
    \date{$(date +"%m/%d/%Y")}
    \maketitle
_EOF_
}

write_end_of_doc(){
    cat <<- _EOF_

\end{document}
_EOF_
}

write_file(){
    write_preamble
    write_body
    write_end_of_doc
}

compile(){
    cd $dir
    pdflatex ./$filename
    cd - > /dev/null
}

usage(){
    echo "usage: $SCRIPT [option]..."    
}

help(){
    usage
    echo "Create a new LaTeX document directory and base document"
    echo
    echo "  -o,  --output              output filename         (filename.tex)"
    echo "  -d,  --directory           directory                       (img/)"
    
    echo "  -t,  --type                document type               (homework)"
    echo "  -c,  --compile             compile the document"
    echo "  -h,  --help                display this help and exit"
    echo
    echo "Visit https://github.com/tdpage/latex_tools for more info"
}

## Main

# initialize some fields
filename=       # filename including extension
directory=      # directory to place file
type=           # document type
compileFlag=    # compile to PDF

# read flags
while [ "$1" != "" ]; do
    case $1 in
        -o | --output    )      shift
                                filename=$1
                                ;;
        -d | --directory )      shift
                                dir=$1
                                ;;
        -t | --type      )      shift
                                type=$1
                                ;;
        -c | --compile   )      compileFlag="1"
                                ;;
        -h | --help      )      help
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

# if certain fields haven't been entered, set some defaults based on the filename
[[ "$filename" = "" ]]    && filename="new_document.tex"
[[ "$dir" = "" ]]         && dir="${filename%.*}/"
[[ "$type" = "" ]]        && type="homework"

# do some work
make_file_structure
[[ -f "./$dir$filename" ]] || write_file > ./$dir$filename
[[ "$compileFlag" ]] && compile
exit 0
