#!/bin/bash

# This script makes a folder structure and basic LaTeX document 

## Constants

RIGHT_NOW="$(date +"%x %r %Z")"
TIME_STAMP="Updated $RIGHT_NOW by $USER"
SCRIPT="$(basename $0)"

TEMPLATEDIR="/home/$USER/bin/latex_tools/templates/"

## Functions

make_file_structure(){
    [ -d "./$dir" ] || mkdir "./$dir"
    for subdir in img circuit table tex appendix; do
        [ -d "./$dir$subdir" ] || mkdir -p "./$dir$subdir"
    done
}



default="
% $TIME_STAMP

%--Preamble-------------------------------------------------------------
\documentclass{scrartcl}

%--Body-----------------------------------------------------------------
\begin{document}

\end{document}
"

function load_template(){
    if [ $type = "default" ] 
    then
        template=$default
    else
        template=$(cat "$TEMPLATEDIR$type.tex") || EXIT_CODE=$?
        # Catch an exit code if the template load was successful or not
        case $EXIT_CODE in
            
            # unsuccessful, fall back to default
            1 )             echo "$type template not found in $TEMPLATEDIR!"
                            echo "Falling back to default template"
                            template=$default
                            ;;
            # successful, preform replacement of items
            0 )             template=${template//'$TIME_STAMP'/$TIME_STAMP}
                            template=${template//'$title'/$title}
                            template=${template//'$subtitle'/$subtitle}
                            template=${template//'$author'/$author}
                            template=${template//'$date'/$date}
                            ;;
        esac
    fi
    
}

function write_file(){

    echo "$template"
}

function compile(){
    cd $dir
    pdflatex ./$filename
    cd - > /dev/null
}

function usage(){
    echo "usage: $SCRIPT [option]..."    
}

function help(){
    usage
    echo "Create a new LaTeX document directory and base document"
    echo
    echo "  -o,  --output              output filename         (filename.tex)"
    echo "  -d,  --directory           directory name                  (img/)"
    echo "  -t,  --title               document title           (Homework 05)"
    echo "  -s,  --subtitle            document subtitle             (EE4252)"
    echo "  -a,  --author              document author           (Fred Jones)"
    echo "  -D,  --date                document date            (Spring 2020)"
    echo "  -T,  --type                document type               (homework)"
    echo "  -c,  --compile             compile the document"
    echo "  -h,  --help                display this help and exit"
    echo
    echo "Visit https://github.com/tdpage/latex_tools for more info"
}

## Main

# initialize some fields
filename=       # filename including extension
directory=      # directory to place file
title=          # document title
subtitle=       # document subtitle
author=         # document author
date=           # date
type=           # document type
compileFlag=    # compile to PDF

# read flags
while [ "$1" != "" ]; do
    case $1 in
        -o | --output    )      shift
                                filename=$1
                                ;;
        -d | --directory )      shift
                                dir=$1
                                ;;
        -t | --title     )      shift
                                title=$1
                                ;;                  
        -s | --subtitle  )      shift
                                subtitle=$1
                                ;;
        -a | --author     )     shift
                                author=$1
                                ;;
        -D | --date      )      shift
                                date=$1
                                ;;
        -T | --type      )      shift
                                type=$1
                                ;;
        -c | --compile   )      compileFlag="1"
                                ;;
        -h | --help      )      help
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

# if certain fields haven't been entered, set some defaults based on the filename
[[ "$filename" = "" ]]    && filename="new_document.tex"
[[ "$dir" = "" ]]         && dir="${filename%.*}/"
[[ "$type" = "" ]]        && type="default"
[[ "$title" = "" ]]       && title="Title"
[[ "$subtitle" = "" ]]    && subtitle="Subtitle"
[[ "$author" = "" ]]      && author="Author"
[[ "$date" = "" ]]        && date=$(date +%m/%d/%Y)

# do some work
make_file_structure
load_template

[[ -f "./$dir$filename" ]] || write_file > ./$dir$filename
[[ "$compileFlag" ]] && compile
exit 0
